/* empty css                      */import{i as l,S as u}from"./assets/vendor-IZ_vzB-l.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const f=document.getElementById("search-form"),m=document.getElementById("search-input"),d=document.getElementById("gallery"),i=document.getElementById("loader");let a;const p="53016082-e520ad17d921b98237d23020b",h="https://pixabay.com/api/";f.addEventListener("submit",s=>{s.preventDefault();const r=m.value.trim();r&&y(r)});async function y(s){d.innerHTML="",i.classList.remove("hidden");try{const t=await(await fetch(`${h}?key=${p}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`)).json();if(i.classList.add("hidden"),t.hits.length===0){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits)}catch(r){i.classList.add("hidden"),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}}function g(s){const r=s.map(t=>`
    <a class="card" href="${t.largeImageURL}">
      <img src="${t.webformatURL}" alt="${t.tags}" />
      <div class="card-info">
        <p>Likes: ${t.likes} | Views: ${t.views}</p>
        <p>Comments: ${t.comments} | Downloads: ${t.downloads}</p>
      </div>
    </a>
  `).join("");d.innerHTML=r,a?a.refresh():a=new u(".gallery a",{captionsData:"alt",captionDelay:250})}
//# sourceMappingURL=index.js.map
